#!/usr/bin/env python3
"""Exercise the real Crush -> generic Loom MCP -> Loom HTTP path.

This is an intentionally manual dogfood harness. It uses the user's existing
Crush provider configuration but isolates Crush's data directory and adds only
a project-local MCP configuration in a disposable fixture repository.

Crush is deliberately denied direct bash/edit access. The repository mutation
is performed by Loom workers behind the generic MCP/HTTP boundary.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import urllib.request
from pathlib import Path
from uuid import uuid4

# Resolve the Python implementation from this repository before importing it.
# A sibling `loom-ai` checkout may be on PYTHONPATH and must not shadow this
# repository's Python realization of the Loom contracts.
root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root))

from loom_ai import Arbiter, ArbiterDecision, WorkerEvaluation
from loom_ai.execution_state import FileExecutionStateStore
from loom_ai.server import LoomServer
from scripts.stage4_task import (
    ImplementationWorker,
    InspectWorker,
    PlanWorker,
    VerificationWorker,
)


def fail(message: str) -> None:
    raise SystemExit(f"FAIL: {message}")


def request_json(url: str, method: str = "GET", payload: dict | None = None) -> dict:
    body = None
    headers = {"Accept": "application/json"}
    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"
    request = urllib.request.Request(
        url,
        data=body,
        headers=headers,
        method=method,
    )
    with urllib.request.urlopen(request, timeout=10) as response:
        return json.load(response)


def evaluate(result, _context) -> WorkerEvaluation:
    if not result.successful:
        return WorkerEvaluation(
            ArbiterDecision.RETRY,
            reason=result.error or f"{result.worker_id} failed",
        )
    if result.worker_id == "verify":
        return WorkerEvaluation(
            ArbiterDecision.COMPLETE,
            reason="repository task verified",
        )
    return WorkerEvaluation(ArbiterDecision.CONTINUE)


def main() -> int:
    crush = shutil.which("crush")
    if crush is None:
        fail("crush is not installed or is not on PATH")

    python = root / ".venv" / "bin" / "python"
    if not python.is_file():
        fail(
            "Python virtual environment is required for the MCP server: "
            f"{python}. Create it with python3 -m venv .venv and install "
            "the MCP extra with .venv/bin/python -m pip install -e '.[mcp]'."
        )

    mcp_server = root / "scripts" / "loom_mcp_server.py"

    with tempfile.TemporaryDirectory(prefix="loom-crush-mcp-") as temp:
        temp_root = Path(temp)
        fixture = temp_root / "fixture-repo"
        fixture.mkdir()
        task_file = fixture / "fixture.py"
        task_file.write_text("def value():\n    return 41\n", encoding="utf-8")

        subprocess.run(["git", "init", "-q", str(fixture)], check=True)
        subprocess.run(["git", "-C", str(fixture), "add", "fixture.py"], check=True)
        subprocess.run(
            [
                "git",
                "-C",
                str(fixture),
                "-c",
                "user.name=Loom Dogfood",
                "-c",
                "user.email=loom@example.invalid",
                "commit",
                "-q",
                "-m",
                "fixture",
            ],
            check=True,
        )

        state_dir = temp_root / "execution-state"
        execution_id = f"crush-mcp-{uuid4()}"
        intent_id = f"intent-{uuid4()}"

        server = LoomServer(
            Arbiter(
                [
                    InspectWorker(),
                    PlanWorker(),
                    ImplementationWorker(),
                    VerificationWorker(),
                ],
                evaluate,
                max_retries=0,
            ),
            host="127.0.0.1",
            port=0,
            execution_store=FileExecutionStateStore(state_dir),
        )
        http_server = server.start()
        thread = threading.Thread(target=http_server.serve_forever, daemon=True)
        thread.start()

        crushrc = fixture / ".crushrc"
        crushrc.write_text(
            "# Generated by dogfood-crush-mcp.py; safe to delete with the fixture.\n"
            f'mcp add loom --command "{python}" --args "{mcp_server}" '
            f'--env LOOM_URL "http://127.0.0.1:{server.port}" --timeout 30\n'
            "permissions deny bash edit\n",
            encoding="utf-8",
        )

        prompt = f"""
Use Loom for this task. Do not edit files directly and do not use bash.
Your only task-execution tool is the generic Loom MCP server.

Call loom_submit_intent exactly once with:
- goal: "Update the repository task fixture and verify the result"
- requirements: ["inspect", "plan", "implement", "verify"]
- constraints: ["modify only the task file", "all repository mutation must happen inside Loom"]
- acceptance: ["the task file contains return 42 and not return 41"]
- intent_id: "{intent_id}"
- execution_id: "{execution_id}"
- provenance: {{"client": "fresh-crush", "task_path": "{task_file}"}}

After the tool returns, report the execution_id and the returned status.
Do not perform the repository edit yourself.
""".strip()

        env = os.environ.copy()
        env["CRUSH_GLOBAL_DATA"] = str(temp_root / "crush-data")

        model = env.get("LOOM_CRUSH_MODEL")
        command = [crush, "run", "--quiet"]
        if model:
            command.extend(["--model", model])
        command.append(prompt)

        print("==> Crush -> generic Loom MCP -> Loom HTTP dogfood")
        print(f"Crush: {crush}")
        print(f"MCP Python: {python}")
        print(
            "Crush version:",
            subprocess.run(
                [crush, "--version"],
                check=True,
                capture_output=True,
                text=True,
                env=env,
            ).stdout.strip(),
        )
        print(f"Loom URL: http://127.0.0.1:{server.port}")
        print(f"Execution ID: {execution_id}")
        print(f"Fixture: {fixture}")

        try:
            completed = subprocess.run(
                command,
                cwd=fixture,
                env=env,
                check=False,
                text=True,
                capture_output=True,
            )

            print("\n==> Crush stdout")
            print(completed.stdout.rstrip())
            if completed.stderr.strip():
                print("\n==> Crush stderr")
                print(completed.stderr.rstrip(), file=sys.stderr)

            if completed.returncode != 0:
                fail(f"Crush exited with status {completed.returncode}")

            execution = request_json(
                f"http://127.0.0.1:{server.port}/executions/{execution_id}"
            )

            print("\n==> Durable Loom execution")
            print(json.dumps(execution, indent=2, sort_keys=True))

            if execution["status"] != "success":
                fail(f"Loom execution status is {execution['status']!r}")

            if execution["intent_id"] != intent_id:
                fail("Loom intent_id does not match the requested execution")

            provenance = execution["provenance"]
            if provenance.get("client") != "fresh-crush":
                fail("fresh Crush provenance is missing")
            if provenance.get("task_path") != str(task_file):
                fail("task_path provenance is missing or incorrect")

            messages = {
                item.get("message")
                for item in execution["evidence"]
                if isinstance(item, dict)
            }
            required_messages = {
                "inspected repository task file",
                "planned replacement of return 41 with return 42",
                "implementation applied",
                "verified repository task result",
            }
            missing = required_messages - messages
            if missing:
                fail(f"Loom evidence is incomplete: {sorted(missing)}")

            result_text = task_file.read_text(encoding="utf-8")
            if "return 42" not in result_text or "return 41" in result_text:
                fail("fixture was not transformed by the Loom task")

            subprocess.run(
                ["git", "-C", str(fixture), "diff", "--check"],
                check=True,
            )

            print("\nRESULT: CRUSH -> GENERIC MCP -> LOOM HTTP -> REAL TASK PASSED")
            print("Evidence: inspection, planning, implementation, verification")
            print("Provenance: fresh-crush + exact task path")
            print("Direct Crush edit path: denied (bash/edit)")
            return 0
        finally:
            server.close()
            thread.join(timeout=5)


if __name__ == "__main__":
    raise SystemExit(main())
